service: highfives
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-1
functions:
  graphqlHandler:
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
